[package]
name = "plr-test"
version = "0.1.0"
authors = ["Fuyang Liu <liufuyang@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plr = "0.1.6"

[dev-dependencies]
rand = "0.8.1"
